Repository Jackett/Jackett, pull requests merged in 2021-05, with the labels that each got.

#11665 indexer: fix xthor api state, cleaning and removing old dev mode
  src/Jackett.Common/Indexers/Xthor.cs
  src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataXthor.cs
Labels: Enhancement

#11679 abnormal: cleaned login function
  src/Jackett.Common/Indexers/Abnormal.cs
Labels: Enhancement

#11677 norbits: cleaning, removed legacy dev tools.
  src/Jackett.Common/Indexers/NorBits.cs
  src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataNorbits.cs
Labels: Enhancement, Work in Progress

#11690 xthor-api: massive improvements
  src/Jackett.Common/Indexers/Xthor.cs
  src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataXthor.cs
Labels: Enhancement

#11695 xthor: misc enhancements
  src/Jackett.Common/Indexers/Xthor.cs
Labels: Enhancement

#11715 ShizaProject graphql indexer
  src/Jackett.Common/Indexers/ShizaProject.cs
Labels: Work in Progress
